### ISSUE TITLE
PYTHON division by zero error

### ISSUE THREAD

**Issue by BaLaurent** [zertyn/streamr_node_earnings_checker#5]
Hi there's a division by zero error when you've mined since less than 1 day
caused by this :
# average revenue per dag and hour, calculated from total revenue up to current date
rev_day = round(rev_total / mining_days, 2)
rev_hour = round(rev_total / (mining_days * 24 + mining_hours), 2)

i replaced by this and now it work well : 
if(mining_days == 0):   
    rev_day = round(rev_total / mining_hours, 2)
    rev_hour = round(rev_total / mining_hours, 2)
else:
    # average revenue per dag and hour, calculated from total revenue up to current date
    rev_day = round(rev_total / mining_days, 2)
    rev_hour = round(rev_total / (mining_days * 24 + mining_hours), 2)

**Comment by zertyn** [comment]
Thank you for the addition, it has been added!
